version: "3"

services:
  apache: 
    build:
      context: apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
 
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=secret
